apiVersion: sagemaker.aws.amazon.com/v1
kind: HostingDeployment
metadata:
  name: endpoint-name # add unique endpoint name
spec:
  region: <AWS region> # add region where you want to deploy
  productionVariants:
    - variantName: AllTraffic
      modelName: <Model Name> # name of trained model
      initialInstanceCount: 1
      instanceType: ml.t2.medium 
      initialVariantWeight: 1
  models:
    - name: <Model Name> # name of trained model
      executionRoleArn: <Sagemaker Execution Role> # add role
      containers:
        - containerHostname: xgboost
          modelDataUrl: s3://demos-vadimd/sagemaker/DEMO-xgboost/output/demo-job-4/output/model.tar.gz
          image: 825641698319.dkr.ecr.us-east-2.amazonaws.com/xgboost:1

